CREATE OR REPLACE VIEW JOBS.DWH.JOBS_EVOLUTION AS

SELECT 
    JOB_ID,
    TITLE,
    COMPANY,
    CATEGORY,
    URL,
    JOB_TYPE,
    PUBLISHED_AT,

    -- SCD2 Meta
    META_INSERT_DATE,
    META_HASH,
    META_BUSINESS_KEY_HASH,
    META_IS_DELETED,

    -- SCD2 Validity
    META_INSERT_DATE AS META_VALID_FROM,
    NVL(
        DATEADD(DAY, -1, 
            LAG(META_INSERT_DATE) OVER (
                PARTITION BY META_BUSINESS_KEY_HASH 
                ORDER BY META_INSERT_DATE DESC
            )
        ),
        TO_TIMESTAMP('2999-12-31 23:59:59.999')
    ) AS META_VALID_TO,

    DECODE(
        ROW_NUMBER() OVER (
            PARTITION BY META_BUSINESS_KEY_HASH 
            ORDER BY META_INSERT_DATE DESC
        ), 
        1, 1, 0
    ) AS META_IS_CURRENT,

    ROW_NUMBER() OVER (
        PARTITION BY META_BUSINESS_KEY_HASH 
        ORDER BY META_INSERT_DATE ASC
    ) AS META_VERSION

FROM JOBS.DWH.JOBS_BASE;
