CREATE OR REPLACE VIEW JOBS.DWH.JOBS_CURRENT AS

SELECT *
FROM JOBS.DWH.JOBS_BASE
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY META_BUSINESS_KEY_HASH
    ORDER BY META_INSERT_DATE DESC
) = 1
AND META_IS_DELETED = 0;
